kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j
  labels:
    app: neo4j
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        component: core
    spec:
      containers:
      - name: neo4j
        image: "neo4j:3.2"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: NEO4J_AUTH
          value: "none"
        - name: NEO4J_dbms_connector_bolt_address
          value: "0.0.0.0:7687"
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "3G"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "3G"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7473
          name: https
        - containerPort: 7687
          name: bolt
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: neo4j
