apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
    component: core
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 7474
      protocol: TCP
    - name: https
      port: 7473
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j
    component: core