kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: elastic
  labels:
    app: elastic
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
        component: core
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        env:
        - name: "HTTP_ENABLE"
          value: "true"
        - name: "xpack.security.enabled"
          value: "false"
        - name: "http.cors.enabled"
          value: "true"
        - name: "http.cors.allow-origin"
          value: "*"
        - name: "http.host"
          value: "0.0.0.0"
        - name: "transport.host"
          value: "127.0.0.1"
        - name: "http.enabled"
          value: "true"
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: elastic
