apiVersion: v1
kind: Service
metadata:
  name: elastic
  labels:
    component: elastic
spec:
  type: LoadBalancer
  selector:
    app: elastic
    component: core
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP