version: '3'
services:
  neo4j:
    image: neo4j:3.2
    restart: always
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - elastic=http://elastic
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
  rabbitmq:
    image: rabbitmq:3.6.12-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=architect
      - RABBITMQ_DEFAULT_PASS=gotpublicdata
    ports:
      - 5672:5672
      - 15672:15672
