apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.6.3
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elastic:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "changeme"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP