kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "rabbitmq:3.6.12-management"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
          name: main
        - containerPort: 15672
          name: web
        securityContext:
          privileged: true
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
