apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: main
      port: 5672
      protocol: TCP
    - name: web
      port: 15672
      protocol: TCP
  selector:
    component: rabbitmq